sudo: false
language: python
python:
- '2.7'
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.6
    - python3.5
#    - python3.6
before_install:
- pip install -r requirements.txt
- pip install pycodestyle
script:
- pycodestyle --max-line-length=160 --config=/dev/null --ignore=E305,E402,E722,E741 module_utils/__init__.py $(git diff --name-only $TRAVIS_COMMIT_RANGE | grep '.py$')
- python2.6 -m compileall library/ module_utils/
- python2.7 -m compileall library/ module_utils/
- python3.5 -m compileall library/ module_utils/
#- python3.6 -m compileall library/ module_utils/
